id: A63059A83
title: Prayer for the Long Life of Dzongsar Jamyang Khyentse Rinpoche
type: translation
pechas:
- I5FBC6A94
- I6C674C9E
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:50:58.289783
  last_modified_at: 2023-01-04 11:50:58.289798
  collections:
  - Dzongsar Khyentse Rinpoche
  - Works of Tibetan Masters
alignment_to_base:
  I5FBC6A94/3981: F451
  I6C674C9E/4578: F451
